model_type: 'trav' # 'trav', 'image', 'fusion'

dimensions:
  action_dim: 3

training:
  batch_size: 16
  epochs: 70
  lr: 3e-6
  df: /home/pcgta/Documents/cs6670finalproject/anymalrunner/bc_data
  device: 'cuda'